config/routes.rb
Rails.application.routes.draw do
  get 'admins/index'
  root 'questions#home'
  devise_for :users
  get 'careers/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :questions
resources :careers, only: [:index]
  get 'contact' => 'contacts#index'

resources :quiz_submissions, only: [:create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/career.rb
class Career < ApplicationRecord
     # before_action :authenticate_user!
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :choices, dependent: :destroy


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_controller.rb
# class AdminsController < ApplicationController
#   before_action :admin_user
#
#   def index
#   end
#
#   private
#
#   def admin_user
#       unless current_user.admin?
#           redirect_to root_path
#       end
#   end
#
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!, :except => [:show_cont, :home]
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController

  def index
    @careers = Career.all
  end
  def show
    @career = Career.find(params[:id])
  end



end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController


  def index
    @choices = Choice.all
  end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


  def index
  end


end

app/controllers/home_controller.rb
class HomeController < ActionController::Base

  def show_cont
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController


  def index
    @questions = Question.all
    @choices = Choice.all
  end

  private
  def filter_admin
      redirect_to admins_index_path if current_user.admin?
  end
end

app/controllers/quiz_submissions_controller.rb
class QuizSubmissionsController < ApplicationController


  def create
    ##figure out the career
    if params[:question_1] == "1" && params[:question_2] == "4" && params[:question_3] == "5" #question answers
      @career = [Career.find(4), Career.find(8)] #career
      render 'careers/show'
    elsif params[:question_1] == "1" && params[:question_2] == "4" && params[:question_3] == "5" #question answers
      @career = [Career.find(8), Career.find(4)] #career
      render 'careers/show'
    elsif params[:question_1] == "1" && params[:question_2] == "4" && params[:question_3] == "6" #question answers
      @career = [Career.find(1), Career.find(5)] #career
      render 'careers/show'
    elsif params[:question_1] == "1" && params[:question_2] == "4" && params[:question_3] == "6" #question answers
      @career = [Career.find(5), Career.find(1)] #career
      render 'careers/show'
    elsif params[:question_1] == "1" && params[:question_2] == "3" && params[:question_3] == "5" #question answers
      @career = [Career.find(7), Career.find(3)] #career
      render 'careers/show'
    elsif params[:question_1] == "1" && params[:question_2] == "3" && params[:question_3] == "5" #question answers
      @career = [Career.find(3), Career.find(7)] #career
      render 'careers/show'
    elsif params[:question_1] == "1" && params[:question_2] == "3" && params[:question_3] == "6" #question answers
      @career = [Career.find(2), Career.find(6)] #career
      render 'careers/show'
    elsif params[:question_1] == "1" && params[:question_2] == "3" && params[:question_3] == "6" #question answers
      @career = [Career.find(6), Career.find(2)] #career
      render 'careers/show'
    elsif params[:question_1] == "2" && params[:question_2] == "4" && params[:question_3] == "5" #question answers
      @career = [Career.find(15), Career.find(16)] #career
      render 'careers/show'
    elsif params[:question_1] == "2" && params[:question_2] == "4" && params[:question_3] == "5" #question answers
      @career = [Career.find(16), Career.find(15)] #career
      render 'careers/show'
    elsif params[:question_1] == "2" && params[:question_2] == "4" && params[:question_3] == "6" #question answers
      @career = [Career.find(12), Career.find(11)] #career
      render 'careers/show'
    elsif params[:question_1] == "2" && params[:question_2] == "4" && params[:question_3] == "6" #question answers
      @career = [Career.find(11), Career.find(12)] #career
      render 'careers/show'
    elsif params[:question_1] == "2" && params[:question_2] == "3" && params[:question_3] == "5" #question answers
      @career = [Career.find(14), Career.find(9)] #career
      render 'careers/show'
    elsif params[:question_1] == "2" && params[:question_2] == "3" && params[:question_3] == "5" #question answers
      @career = [Career.find(9), Career.find(14)] #career
      render 'careers/show'
    elsif params[:question_1] == "2" && params[:question_2] == "3" && params[:question_3] == "6" #question answers
      @career = [Career.find(13), Career.find(10)] #career
      render 'careers/show'
    elsif params[:question_1] == "2" && params[:question_2] == "3" && params[:question_3] == "6" #question answers
      @career = [Career.find(10), Career.find(13)] #career
      render 'careers/show'
    else
      redirect_to contact_path
    end
  end

  def show
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/views/admins/index.html.erb
<!-- <h1 class="title">Promote Your Opportunity On Your Next Move!</h1>
    <hr>

<form>
      <div class="form-group nameEmailInput">
        <label for="name">Name:</label>
        <input type="name" class="form-control" id="exampleInputName1" aria-describedby="nameHelp" placeholder="First Last">
      </div>
      <div class="form-group nameEmailInput">
        <label for="exampleInputEmail1">Email:</label>
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="email@email.com">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group phoneInput">
        <label for="exampleInputPhone1">Phone:</label>
        <input type="phone" class="form-control" id="exampleInputPhone1" placeholder="XXX-XXX-XXXX">
        <small id="phoneHelp" class="form-text text-muted">Optional.</small>
      </div>

  <div class="form-group submissionSelect">
    <label for="exampleSelect1">What Type Of Opportunity?</label>
    <select class="form-control" id="exampleSelect1">
      <option></option>
      <option>Apprenticeship</option>
      <option>Immediate Hire</option>
      <option>Internship</option>
      <option>Certification Course</option>
    </select>
  </div>
  <div class="form-group">
    <label for="textArea">Give Us The Details:</label>
    <textarea class="form-control" id="TxtArea" rows="3"></textarea>
  </div>
  </label>
</div>
<br>
<div class="float-right">
  <button type="submit" class="btn btn-primary">Submit</button>
</div>
</form> -->

app/views/careers/index.html.erb
<a class="btn-outline-info">
  <h1 class="title">Job List</h1>
<hr>
  <div class="jobList">
      <% @careers.each do |career| %>
      <div class='shit'>
          <%= image_tag "/images/#{career.title}.jpg", :class => "rounded float-right" %>
              <div class="title"> <h3><%= career.title %></h3> </div>
              <div class="description"> <%= career.description %> </div>
              <div> <%= "Starting Salary: #{number_to_currency(career.starting_salary)}" %> </div>
              <div> <%= "Potential Salary: #{number_to_currency(career.potential_salary)}" %> </div>
              <div> <%= "Education Requirements/Options: #{career.education}" %> </div>
          <div class="spacer"></div>
          <br>
          <!-- JOBS Button trigger modal -->
          <button type="button" class="fuck btn btn-success" data-toggle="modal" data-target="#exampleModal<%=career.title.delete(' ').camelize%>">
          See Jobs in Your Area!
          </button>

          <!-- Jobs Modal -->
          <div class="modal" id="exampleModal<%=career.title.delete(' ').camelize%>" tabindex="-1" role="dialog">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel"><%= career.title %></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="job-content modal-body">

              </div>
              <div class="modal-footer">
                  <a class="btn btn-success" href="https://www.glassdoor.com/index.htm" role="button">See More Jobs on GlassDoor!</a>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
              </div>
          </div>
          </div>
          <div class="spacer"></div>
          <div class="spacer"></div>
          <br>
           <!-- SCHOOLS Button trigger modal -->
          <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal2<%=career.title.delete(' ').camelize%>">
          Trade Schools Near You!
          </button>

          <!-- Schools Modal -->
          <div class="modal" id="modal2<%=career.title.delete(' ').camelize%>" tabindex="-1" role="dialog">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="modal2Label"><%= career.title %></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="school-content modal-body">
                  <%= career.title %> trade schools near your provide an excellent opportunity for you to excell and create a new career.
              </div>
              <div class="modal-footer">
                  <a class="btn btn-success" href="https://www.trade-schools.net/locations/" role="button">Find More Schools!</a>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
              </div>
          </div>
          </div>
          <div class="spacer"></div>
          <hr>
          <br />
          </div>
      <% end %>
            <script>


                      async function searchJobs(job) {
                        let results = await axios.get(`https://jobs.search.gov/jobs/search.json?query=${job}+jobs`);
                        return results
                      }


                      $('.fuck').on('click', function(){
                          let job = $(this).parents('.shit').find('h3').get(0).innerText

                          let res = searchJobs(job)
                          res.then(({data}) => {
                              let f = $(this).parents('.shit').find('.job-content')

                              data.map(ass => {
                                  f.append(
                                   '<h4 class="assTitle">' + ass.position_title + '<br>' +
                                   '<h6 class="assJob">' + ass.organization_name + '</h6>' + '<br>' + 
                                   '<h6 class="assPay">' + ass.maximum.toLocaleString('en-US', { style: 'currency', currency: 'USD' }) + '</h6>' + '<br>' + 
                                   '<a class="assLink" href=' + ass.url + '>' + 'See Full Job Listing' + '</a>' + 
                                   '</h4>' + 
                                   '<hr>')
                              })

                          })

                      })

              </script>
  </div>
<hr>

app/views/careers/show.html.erb
<a class="btn-outline-info">
  <h1 class="title">Your Job List</h1>
<hr>
  <div class="jobList">
      <% @career.each do |career| %>
      <div class='shit'>
          <%= image_tag "/images/#{career.title}.jpg", :class => "rounded float-right" %>
              <div class="title"> <h3><%= career.title %></h3> </div>
              <div class="description"> <%= career.description %> </div>
              <div> <%= "Starting Salary: #{number_to_currency(career.starting_salary)}" %> </div>
              <div> <%= "Potential Salary: #{number_to_currency(career.potential_salary)}" %> </div>
              <div> <%= "Education Requirements/Options: #{career.education}" %> </div>
          <div class="spacer"></div>
          <br>
          <!-- JOBS Button trigger modal -->
          <button type="button" class="fuck btn btn-success" data-toggle="modal" data-target="#exampleModal<%=career.title.delete(' ').camelize%>">
          See Jobs in Your Area!
          </button>

          <!-- Jobs Modal -->
          <div class="modal" id="exampleModal<%=career.title.delete(' ').camelize%>" tabindex="-1" role="dialog">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel"><%= career.title %></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="job-content modal-body">

              </div>
              <div class="modal-footer">
                  <a class="btn btn-success" href="https://www.glassdoor.com/index.htm" role="button">See More Jobs on GlassDoor!</a>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
              </div>
          </div>
          </div>
          <div class="spacer"></div>
          <div class="spacer"></div>
          <br>
           <!-- SCHOOLS Button trigger modal -->
          <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal2<%=career.title.delete(' ').camelize%>">
          Trade Schools Near You!
          </button>

          <!-- Schools Modal -->
          <div class="modal" id="modal2<%=career.title.delete(' ').camelize%>" tabindex="-1" role="dialog">
          <div class="modal-dialog" role="document">
              <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="modal2Label"><%= career.title %></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="school-content modal-body">
                  <%= career.title %> trade schools near your provide an excellent opportunity for you to excell and create a new career.
              </div>
              <div class="modal-footer">
                  <a class="btn btn-success" href="https://www.trade-schools.net/locations/" role="button">Find More Schools!</a>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
              </div>
          </div>
          </div>
          <div class="spacer"></div>
          <hr>
          <br />
          </div>
      <% end %>
            <script>


                      async function searchJobs(job) {
                        let results = await axios.get(`https://jobs.search.gov/jobs/search.json?query=${job}+jobs`);
                        return results
                      }


                      $('.fuck').on('click', function(){
                          let job = $(this).parents('.shit').find('h3').get(0).innerText

                          let res = searchJobs(job)
                          res.then(({data}) => {
                              let f = $(this).parents('.shit').find('.job-content')

                              data.map(ass => {
                                  f.append(
                                   '<h4 class="assTitle">' + ass.position_title + '<br>' +
                                   '<h6 class="assJob">' + ass.organization_name + '</h6>' + '<br>' + 
                                   '<h6 class="assPay">' + ass.maximum.toLocaleString('en-US', { style: 'currency', currency: 'USD' }) + '</h6>' + '<br>' + 
                                   '<a class="assLink" href=' + ass.url + '>' + 'See Full Job Listing' + '</a>' + 
                                   '</h4>' + 
                                   '<hr>')
                              })

                          })

                      })

              </script>
  </div>
<hr>

app/views/choices/index.html.erb
<a class="btn-outline-info">
      <% if user_signed_in? %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
      <% end %>

app/views/contacts/index.html.erb
<h1 class="title">Contact Us</h1>
    <hr>

<form>
      <div class="form-group nameEmailInput">
        <label for="name">Name:</label>
        <input type="name" class="form-control" id="exampleInputName1" aria-describedby="nameHelp" placeholder="First Last">
      </div>
      <div class="form-group nameEmailInput">
        <label for="exampleInputEmail1">Email:</label>
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="email@email.com">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group phoneInput">
        <label for="exampleInputPhone1">Phone:</label>
        <input type="phone" class="form-control" id="exampleInputPhone1" placeholder="XXX-XXX-XXXX">
        <small id="phoneHelp" class="form-text text-muted">Optional.</small>
      </div>
      
  <div class="form-group submissionSelect">
    <label for="exampleSelect1">Select One:</label>
    <select class="form-control" id="exampleSelect1">
      <option></option>
      <option>Question</option>
      <option>Comment</option>
      <option>Career Opportunity</option>
      <option>Student Help</option>
      <option>School Help</option>
    </select>
  </div>
  <div class="form-group">
    <label for="textArea">What Would You Like Us To Know?</label>
    <textarea class="form-control" id="TxtArea" rows="3"></textarea>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <input type="checkbox" class="form-check-input">
      <span class="checkboxSpace">
        I'd like to receive email updates about Your Next Move's upcoming events.
      </span>
    </label>
  </div>
  <div class="form-check">
  <label class="form-check-label">
    <input type="checkbox" class="form-check-input">
      <span class="checkboxSpace">
        I'd like to receive text updates about Your Next Move's upcoming events.
      </span>
  </label>
</div>
<br>
<div class="float-right">
  <button type="submit" class="btn btn-primary">Submit</button>
<br>
<br>
<br>
<hr>
</div>
</form>

app/views/home/index.html.erb
<p> HELLO </p> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PitchProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
      <div class="navBar">
          <a name="top"></a>
          <a class="btn btn-outline-info" href="/" role="button">Home</a>
          <a class="btn btn-outline-info" href="/questions" role="button">Take Our Test!</a>
          <a class="btn btn-outline-info" href="/careers" role="button">See Your Next Job!</a>
          <a class="btn btn-outline-info" href="/contact" role="button">Contact Us!</a>

            <% if user_signed_in? %>
              <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn-outline-info" %>
            <% end %>
      </div>
      <div class="float-right">
        <%= link_to image_tag("yourNextMoveLogo/smallYnmLogo.jpg"), root_path %>
      </div>
    <div>
      <%= yield %>
    </div>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/questions/home.html.erb
<h1 class="title">Your Next Move</h1>
<hr>
    <div>
      <img src="/images/homeStat1.jpg" class="sideBar1">
      <img src="/images/homeStat2.jpg" class="sideBar2">
    </div>

  <div id="homePageCenterImage">
      <img src="/images/dreamToDesign.jpg">
      <div id="homePageCenterImageText">
        <h1 class= "title">Find Where You Belong</h1>
        <p class="title">UX/UI and other Design Focused careers are always in demand</p>
        <p><a href="/careers" class="btn btn-info btn-sm">Find Out More</a></p>
      </div>
  </div>
      <div class="downArrow bounce">
        <img width="40" height="40" alt="" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/PjwhRE9DVFlQRSBzdmcgIFBVQkxJQyAnLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4nICAnaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkJz48c3ZnIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDMyIDMyIiBoZWlnaHQ9IjMycHgiIGlkPSLQodC70L7QuV8xIiB2ZXJzaW9uPSIxLjEiIHZpZXdCb3g9IjAgMCAzMiAzMiIgd2lkdGg9IjMycHgiIHhtbDpzcGFjZT0icHJlc2VydmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiPjxwYXRoIGQ9Ik0yNC4yODUsMTEuMjg0TDE2LDE5LjU3MWwtOC4yODUtOC4yODhjLTAuMzk1LTAuMzk1LTEuMDM0LTAuMzk1LTEuNDI5LDAgIGMtMC4zOTQsMC4zOTUtMC4zOTQsMS4wMzUsMCwxLjQzbDguOTk5LDkuMDAybDAsMGwwLDBjMC4zOTQsMC4zOTUsMS4wMzQsMC4zOTUsMS40MjgsMGw4Ljk5OS05LjAwMiAgYzAuMzk0LTAuMzk1LDAuMzk0LTEuMDM2LDAtMS40MzFDMjUuMzE5LDEwLjg4OSwyNC42NzksMTAuODg5LDI0LjI4NSwxMS4yODR6IiBmaWxsPSIjMTIxMzEzIiBpZD0iRXhwYW5kX01vcmUiLz48Zy8+PGcvPjxnLz48Zy8+PGcvPjxnLz48L3N2Zz4=" />
      </div>
<br>
<br>
    <div class="container title homePageFooter">
      <img src="/images/ourPromise.jpg" class="ourPromise">
    </div>
<br>
<br>
<br>

app/views/questions/index.html.erb
<h1 class="title">Test</h1>
<hr>

<%= form_tag quiz_submissions_path do %>
  <div id="test">
    <% @questions.each do |question| %>
        <p><%= question.prompt %></p>
        <p class="testAnswers">
          <%= select_tag "question_#{question.id}",
              options_from_collection_for_select(question.choices, "id", "name") %>
        </p>
    <% end %>
  </div>
  <br>
  <br>
  <br>
  <div class="float-right">
    <%= submit_tag "Submit", class: "btn btn-primary" %>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <hr>

<% end %>